title: Cleverson de Sousa Lima
first_name: Cleverson
middle_name: de Sousa
last_name: Lima
description: Exploring organismal responses to environmental stress, particularly within extreme environments. Research interests include ecology, physiology, and genomics.
url: https://midgecal.com
icon:
