title: "Cleverson de Sousa Lima"
first_name: "Cleverson"
middle_name: "de Sousa"
last_name: "Lima"
description: "Interested in organismal responses to environmental stress, particularly within extreme environments. Research focuses on ecology, physiology, and genomics."
url: "https://midgecal.com"
icon: "⚛️"
blog_name: "Cleverson de Sousa Lima"
blog_description: "Interested in organismal responses to environmental stress, particularly within extreme environments. Research focuses on ecology, physiology, and genomics."